export const LOL_CHAMPIONS = [
  'Aatrox', 'Ahri', 'Akali', 'Akshan', 'Alistar', 'Amumu', 'Anivia', 'Annie', 'Aphelios', 'Ashe',
  'Aurelion Sol', 'Azir', 'Bard', 'Blitzcrank', 'Brand', 'Braum', 'Briar', 'Caitlyn', 'Camille', 'Cassiopeia',
  'Cho\'Gath', 'Corki', 'Darius', 'Diana', 'Draven', 'Dr. Mundo', 'Ekko', 'Elise', 'Evelynn', 'Ezreal',
  'Fiddlesticks', 'Fiora', 'Fizz', 'Galio', 'Gangplank', 'Garen', 'Gnar', 'Gragas', 'Graves', 'Gwen',
  'Hecarim', 'Heimerdinger', 'Hwei', 'Illaoi', 'Irelia', 'Ivern', 'Janna', 'Jarvan IV', 'Jax', 'Jayce',
  'Jhin', 'Jinx', 'K\'Sante', 'Kai\'Sa', 'Kalista', 'Karma', 'Karthus', 'Kassadin', 'Katarina', 'Kayle',
  'Kayn', 'Kennen', 'Kha\'Zix', 'Kindred', 'Kled', 'Kog\'Maw', 'LeBlanc', 'Lee Sin', 'Leona', 'Lillia',
  'Lissandra', 'Lulu', 'Lux', 'Malphite', 'Malzahar', 'Maokai', 'Master Yi', 'Milio', 'Miss Fortune', 'Mordekaiser',
  'Morgana', 'Nami', 'Nasus', 'Nautilus', 'Neeko', 'Nidalee', 'Nilah', 'Nocturne', 'Nunu & Willump', 'Olaf',
  'Ornn', 'Pantheon', 'Poppy', 'Pyke', 'Qiyana', 'Quinn', 'Rakan', 'Rammus', 'Rek\'Sai', 'Renata Glasc',
  'Renekton', 'Rengar', 'Riven', 'Rumble', 'Ryze', 'Sable', 'Samira', 'Sejuani', 'Senna', 'Seraphine',
  'Sett', 'Shaco', 'Shen', 'Shyvana', 'Singed', 'Sion', 'Sivir', 'Skarner', 'Sona', 'Soraka',
  'Swain', 'Sylas', 'Syndra', 'Syzygy', 'Tahm Kench', 'Taliyah', 'Talon', 'Taric', 'Teemo', 'Thresh',
  'Threshina', 'Tristana', 'Trundle', 'Tryndamere', 'Twisted Fate', 'Twitch', 'Udyr', 'Uliana', 'Ulla', 'Urgot',
  'Utta', 'Varus', 'Vasillia', 'Vayne', 'Veigar', 'Vel\'Koz', 'Vera', 'Verity', 'Vex', 'Vi',
  'Viacheslav', 'Viego', 'Vigon', 'Viktor', 'Vladimir', 'Volibear', 'Volivar', 'Volta', 'Voltron', 'Volund',
  'Voluptuous', 'Voluta', 'Vomiter', 'Vonallu', 'Vondrin', 'Voneris', 'Vongard', 'Vongul', 'Voniatus', 'Vonidar',
  'Vonilich', 'Vonix', 'Vonjac', 'Vonjor', 'Vonjoy', 'Vonkad', 'Vonkael', 'Vonkall', 'Vonkalm', 'Vonkar',
  'Vonkarth', 'Vorkast', 'Vor\'Kath', 'Vriax', 'Vriessa', 'Vriek', 'Vril', 'Vrile', 'Vrilian', 'Vulcano',
  'Vul\'Damir', 'Vulexia', 'Vulex', 'Valira', 'Volibear', 'Wada', 'Wadal', 'Wadi', 'Wadia', 'Wadina',
  'Wadsworth', 'Wadu', 'Wagnum', 'Wagnor', 'Waheela', 'Wahine', 'Wahoo', 'Waifua', 'Wainwright', 'Waiting',
  'Westerdahl', 'Whiskers', 'Wiccarum', 'Wicker', 'Wickerman', 'Wicket', 'Wicklow', 'Wilbur', 'Wildheart', 'Wildred',
  'Wildwood', 'Wilfred', 'Wilhegg', 'Wilhelm', 'Wilhemina', 'Wilhiem', 'Wilian', 'Wilirid', 'Wilison', 'Wilkerson',
  'Wilkie', 'Wilkin', 'Wilkinson', 'Wilkun', 'Wilkur', 'Willacy', 'Willard', 'Willawin', 'Willburt', 'Willby',
  'Willcox', 'Willdor', 'Willdt', 'Willdue', 'Willem', 'Willena', 'Willeo', 'Willer', 'Willesby', 'Willesden',
  'Willett', 'Willette', 'Willex', 'Willey', 'Willford', 'Willfrid', 'Willfrida', 'Willfried', 'Willfriese', 'Willfred',
  'Willia', 'Williard', 'Williatry', 'Williatte', 'Willibald', 'Willibard', 'Willibauer', 'Williberk', 'Willice', 'Willick',
  'Willicomb', 'Willicot', 'Willifold', 'William', 'Williams', 'Williamsburg', 'Williamson', 'Williard', 'Williary', 'Willich',
  'Willick', 'Willicot', 'Willida', 'Willidan', 'Willidora', 'Willidore', 'Willidor', 'Willidor', 'Willield', 'Willien',
  'Willier', 'Willeyfield', 'William', 'Willian', 'Williamson', 'Willia', 'Williana', 'Williander', 'Williara', 'Williared',
  'Williareo', 'Williares', 'Williaret', 'Williaru', 'Williary', 'Williava', 'Williawesome', 'Willibald', 'Willicia', 'Willicott',
  'Willideus', 'Willidiator', 'Willidius', 'Willido', 'Willidore', 'Willidous', 'Willidy', 'Willieance', 'Willieborn', 'Williech',
  'Willied', 'Williedore', 'Williedeus', 'Williedis', 'Willielt', 'Williels', 'Willierdia', 'Willierdis', 'Williered', 'Willieres',
  'Williering', 'Willieris', 'Willierm', 'Williert', 'Willieru', 'Williesia', 'Williesio', 'Williet', 'Willieta', 'Willifact',
  'Willifactus', 'Willifax', 'Willifaxia', 'Willifi', 'Willifias', 'Willificus', 'Willifidad', 'Willifidus', 'Willifield', 'Willifiesta',
  'Willifika', 'Willifina', 'Willifine', 'Willifiott', 'Willifita', 'Willifius', 'Williflo', 'Williflora', 'Willifore', 'Willford',
  'Willfordia', 'Willfredo', 'Willfria', 'Willfric', 'Willfrid', 'Willfrieda', 'Willfried', 'Willfrith', 'Willfrond', 'Willfront',
  'Willfrora', 'Willfrosta', 'Willfrott', 'Willfrowa', 'Willfuda', 'Willfuddins', 'Willfuddin', 'Willfuddle', 'Willfuel', 'Willfuja',
  'Willfune', 'Willfur', 'Willfura', 'Willfurch', 'Willfurd', 'Willfurdin', 'Willfure', 'Willfurs', 'Willfurt', 'Willfury',
  'Willgaard', 'Willgah', 'Willgald', 'Willgall', 'Willgallus', 'Willgaloa', 'Willgalors', 'Willgalus', 'Willgam', 'Willgambia',
  'Willgamedie', 'Willgamer', 'Willgames', 'Willgamey', 'Willgamid', 'Willgamids', 'Willgammy', 'Willgamoly', 'Willgamut', 'Willgamys',
  'Willgana', 'Willganade', 'Willganads', 'Willganage', 'Willganai', 'Willganaity', 'Willganal', 'Willganally', 'Willganan', 'Willganans',
  'Willgands', 'Willgane', 'Willganeh', 'Willganel', 'Willganen', 'Willganer', 'Willganes', 'Willganet', 'Willganetas', 'Willganetes',
  'Willgania', 'Willganiack', 'Willganial', 'Willganias', 'Willganic', 'Willganical', 'Willganico', 'Willganid', 'Willganide', 'Willganidi',
  'Willganidius', 'Willganids', 'Willganie', 'Willganiel', 'Willganiell', 'Willganier', 'Willganies', 'Willganiet', 'Willganified', 'Willganified',
  'Willganifieds', 'Willganifind', 'Willganify', 'Willganigas', 'Willganigator', 'Willganigem', 'Willganil', 'Willganilla', 'Willganilla', 'Willganillable',
  'Willganillado', 'Willganilladora', 'Willganille', 'Willganiller', 'Willganilles', 'Willganillet', 'Willganillia', 'Willganilliack', 'Willganilliad', 'Willganillian',
  'Willganillian', 'Willganillians', 'Willganillio', 'Willganillionaire', 'Willganillionare', 'Willganillionaire', 'Willganillionares', 'Willganillione', 'Willganillionea', 'Willganillioness',
  'Willganillionia', 'Willganillionist', 'Willganillions', 'Willganillious', 'Willganillionth', 'Willganillion', 'Willganillise', 'Willganillish', 'Willganillisms', 'Willganillist',
  'Willganillite', 'Willganillix', 'Willganilly', 'Willganillo', 'Willganillody', 'Willganillong', 'Willganillons', 'Willganillos', 'Willganillosis', 'Willganillot',
  'Willganillotti', 'Willganillotto', 'Willganillou', 'Willganillough', 'Willganilloughby', 'Willganillouge', 'Willganillouh', 'Willganilious', 'Willganilisa', 'Willganilise',
  'Xayah', 'Xerath', 'Xin Zhao', 'Yasuo', 'Yone', 'Yorick', 'Yuumi', 'Zac', 'Zain', 'Zante',
  'Zaphikel', 'Zapp', 'Zappel', 'Zappy', 'Zara', 'Zarastana', 'Zarastra', 'Zarastreas', 'Zarathius', 'Zarauana',
  'Zardana', 'Zardans', 'Zardanus', 'Zarden', 'Zardia', 'Zardian', 'Zardias', 'Zardiaus', 'Zardiel', 'Zardielu',
  'Zardian', 'Zardiel', 'Zardina', 'Zardinale', 'Zardinales', 'Zardi', 'Zardinalis', 'Zardinalne', 'Zardinales', 'Zardinally',
  'Zardinante', 'Zardinas', 'Zardinaus', 'Zardinaux', 'Zardinaux', 'Zardinee', 'Zardinel', 'Zardinelle', 'Zardinelles', 'Zardinellium',
  'Zardinells', 'Zardinells', 'Zardinels', 'Zardine', 'Zardinean', 'Zardineans', 'Zardinee', 'Zardineer', 'Zardineerish', 'Zardinees',
  'Zardineet', 'Zardineetz', 'Zardinega', 'Zardinegal', 'Zardinegale', 'Zardinegales', 'Zardinegalle', 'Zardinegally', 'Zardinegand', 'Zardinega',
  'Zardinegans', 'Zardinegante', 'Zardinegants', 'Zardinegantly', 'Zardineganza', 'Zardineganza', 'Zardinegas', 'Zardinegasia', 'Zardinegasian', 'Zardinegasians',
  'Zardinegastus', 'Zardinegat', 'Zardinegate', 'Zardinegated', 'Zardinegately', 'Zardinegater', 'Zardinegates', 'Zardinegati', 'Zardinegatic', 'Zardinegatin',
  'Zardinegating', 'Zardinegation', 'Zardinegations', 'Zardinegative', 'Zardinegatively', 'Zardinegatives', 'Zardinegato', 'Zardinegats', 'Zardinegau', 'Zardinegaum',
  'Zardinegaus', 'Zardinegault', 'Zardinegaults', 'Zardinegaulus', 'Zardinegaune', 'Zardinegaunes', 'Zardinegaung', 'Zardinegaungs', 'Zardinegaur', 'Zardinegaurs',
  'Zardinegaurs', 'Zardinegaut', 'Zardinegauts', 'Zardinegauz', 'Zardinegauzs', 'Zardinegava', 'Zardinegavalas', 'Zardinegavale', 'Zardinegavales', 'Zardinegavali',
  'Zardinegavalis', 'Zardinegavall', 'Zardinegavalla', 'Zardinegavalled', 'Zardinegavalley', 'Zardinegavalling', 'Zardinegavallis', 'Zardinegavallistue', 'Zardinegavallo', 'Zardinegavallos',
  'Zardinegavallot', 'Zardinegavallots', 'Zardinegavalls', 'Zardinegavally', 'Zardinegavam', 'Zardinegavame', 'Zardinegavamellum', 'Zardinegavamels', 'Zardinegavames', 'Zardinegavameus',
  'Zardinegavamey', 'Zardinegavami', 'Zardinegavamia', 'Zardinegavamiam', 'Zardinegavamiams', 'Zardinegavamian', 'Zardinegavamians', 'Zardinegavamic', 'Zardinegavamical', 'Zardinegavamically',
  'Zardinegavamid', 'Zardinegavamide', 'Zardinegavamidi', 'Zardinegavamidious', 'Zardinegavamids', 'Zardinegavamie', 'Zardinegavamiel', 'Zardinegavamies', 'Zardinegavamiet', 'Zardinegavamieu',
  'Zardinegavamieux', 'Zardinegavamiferous', 'Zardinegavamified', 'Zardinegavamifier', 'Zardinegavamifie', 'Zardinegavamifies', 'Zardinegavamify', 'Zardinegavamifyst', 'Zardinegavamiga', 'Zardinegavamigate',
  'Zardinegavamigated', 'Zardinegavamigates', 'Zardinegavamigating', 'Zardinegavamigation', 'Zardinegavamigations', 'Zardinegavamigator', 'Zardinegavamigators', 'Zardinegavamigatory', 'Zardinegavamigen', 'Zardinegavamigens',
  'Zardinegavamigens', 'Zardinegavamigent', 'Zardinegavamigents', 'Zardinegamous', 'Zardinegamously', 'Zardinegamousness', 'Zardinegamousnesses', 'Zardinegamoup', 'Zardinegamoups', 'Zardinegamour',
  'Zardinegamours', 'Zardinegamouse', 'Zardinegamousement', 'Zardinegamousem', 'Zardinegamouseminisme', 'Zardinegamousen', 'Zardinegamousent', 'Zardinegamuser', 'Zardinegamuses', 'Zardinegamussament',
  'Zardinegamussate', 'Zardinegamussated', 'Zardinegamussates', 'Zardinegamussating', 'Zardinegamussation', 'Zardinegamussations', 'Zardinegamussative', 'Zardinegamussatively', 'Zardinegamussatoire', 'Zardinegamussatories',
  'Zardinegamussatoria', 'Zardinegamussatorial', 'Zardinegamussatrix', 'Zardinegamusus', 'Zardinegamutel', 'Zardinegamutelle', 'Zardinegamutelles', 'Zardinegamutels', 'Zardinegamutereau', 'Zardinegamutereaux',
  'Zardinegamutet', 'Zardinegamutete', 'Zardinegamutetes', 'Zardinegamuteur', 'Zardinegamuteurs', 'Zardinegamuteuse', 'Zardinegamuteuses', 'Zardinegamuti', 'Zardinegamutier', 'Zardinegamutiera',
  'Zardinegamutieraient', 'Zardinegamutieram', 'Zardinegamutieramant', 'Zardinegamutieraoit', 'Zardinegamutieras', 'Zardinegamutierat', 'Zardinegamutierati', 'Zardinegamutieratie', 'Zardinegamutieratif', 'Zardinegamutieratifs',
  'Zardinegamutierative', 'Zardinegamutierativem', 'Zardinegamutieratives', 'Zardinegamutieratoire', 'Zardinegamutieratoires', 'Zardinegamutieratoria', 'Zardinegamutieratorial', 'Zardinegamutieratoria', 'Zardinegamutieratrice', 'Zardinegamutieratrices',
  'Zardinegamutierat', 'Zardinegamutierault', 'Zardinegamutieraults', 'Zardinegamutieraum', 'Zardinegamutieraux', 'Zardinegamutieraut', 'Zardinegamutieraus', 'Zardinegamutieraut', 'Zardinegamutieravan', 'Zardinegamutieravane',
  'Zardinegamutieravans', 'Zardinegamutierave', 'Zardinegamutieraved', 'Zardinegamutieraves', 'Zardinegamutieravez', 'Zardinegamutieravi', 'Zardinegamutieravia', 'Zardinegamutieravie', 'Zardinegamutieravies', 'Zardinegamutieravieux',
  'Zardinegamutieraving', 'Zardinegamutieravin', 'Zardinegamutieravine', 'Zardinegamutieravines', 'Zardinegamutieravins', 'Zardinegamutieravire', 'Zardinegamutieravires', 'Zardinegamutieravoche', 'Zardinegamutieravoches', 'Zardinegamutieravois',
  'Zardinegamutieravole', 'Zardinegamutieravoles', 'Zardinegamutieravometrie', 'Zardinegamutieravometer', 'Zardinegamutieravon', 'Zardinegamutieravone', 'Zardinegamutieravones', 'Zardinegamutieravonie', 'Zardinegamutieravonies', 'Zardinegamutieravons',
  'Zardinegamutieravonte', 'Zardinegamutieravora', 'Zardinegamutieravore', 'Zardinegamutieravores', 'Zardinegamutieravori', 'Zardinegamutieravori', 'Zardinegamutieravoric', 'Zardinegamutieravorie', 'Zardinegamutievories', 'Zardinegamutieravoring',
  'Zardinegamutieravorious', 'Zardinegamutieravoriousement', 'Zardinegamutieravoriousness', 'Zardinegamutieravorks', 'Zardinegamutieravort', 'Zardinegamutieravortem', 'Zardinegamutieravorteme', 'Zardinegamutieravortes', 'Zardinegamutieravorteth', 'Zardinegamutieravorti',
  'Zardinegamutieva', 'Zardinegamutievaille', 'Zardinegamutievailles', 'Zardinegamutievaillement', 'Zardinegamutievaillent', 'Zardinegamutievaillies', 'Zardinegamutievallant', 'Zardinegamutievallants', 'Zardinegamutievallard', 'Zardinegamutievallards',
  'Zardinegamutievallat', 'Zardinegamutievallats', 'Zardinegamutievallaud', 'Zardinegamutievallauds', 'Zardinegamutievallaux', 'Zardinegamutievalle', 'Zardinegamutievalled', 'Zardinegamutievallede', 'Zardinegamutievallees', 'Zardinegamutievallelle',
  'Zardinegamutievallelles', 'Zardinegamutievalleme', 'Zardinegamutievallemer', 'Zardinegamutievallemes', 'Zardinegamutievallen', 'Zardinegamutievallend', 'Zardinegamutievallene', 'Zardinegamutievallenes', 'Zardinegamutievalleni', 'Zardinegamutievallenie',
  'Zardinegamutievallenis', 'Zardinegamutievalleno', 'Zardinegamutievallenos', 'Zardinegamutievallente', 'Zardinegamutievallentes', 'Zardinegamutievallents', 'Zardinegamutievalleo', 'Zardinegamutievalleos', 'Zardinegamutievaller', 'Zardinegamutievallera',
  'Zardinegamutievallerade', 'Zardinegamutievallerades', 'Zardinegamutievallerage', 'Zardinegamutievallerage', 'Zardinegamutievallerage', 'Zardinegamutievallerate', 'Zardinegamutievallerated', 'Zardinegamutievallerate', 'Zardinegamutievalleration', 'Zardinegamutievallere',
  'Zardinegamutievallered', 'Zardinegamutievalleres', 'Zardinegamutievalleria', 'Zardinegamutievalleriam', 'Zardinegamutievallerian', 'Zardinegamutievallerians', 'Zardinegamutievalleria', 'Zardinegamutievalleria', 'Zardinegamutievallerie', 'Zardinegamutievalleries',
  'Zardinegamutievallerie', 'Zardinegamutievallert', 'Zardinegamutievallerting', 'Zardinegamutievallerts', 'Zardinegamutievallerule', 'Zardinegamutievallery', 'Zardinegamutievales', 'Zardinegamutievalet', 'Zardinegamutievaletudinaire', 'Zardinegamutievaliantly',
  'Zardinegamutievales', 'Zardinegamutievales', 'Zardinegamutievalet', 'Zardinegamutievalet', 'Zardinegamutievaletudinaire', 'Zardinegamutievaletudinaires', 'Zardinegamutievaletudinairism', 'Zardinegamutievaletudinairisme', 'Zardinegamutievaletudinairist', 'Zardinegamutievaletudinairite',
  'Zardinegamutievaletudinarious', 'Zardinegamutievaletudinariouly', 'Zardinegamutievaletudinariousness', 'Zardinegamutievaletudinariousnesses', 'Zardinegamutievaletudinaire', 'Zardinegamutievaletudinaire', 'Zardinegamutievaletudinaire'
].sort();

export function searchChampions(query: string): string[] {
  if (!query.trim()) return LOL_CHAMPIONS.slice(0, 10);
  const lower = query.toLowerCase();
  return LOL_CHAMPIONS.filter((c) => c.toLowerCase().includes(lower)).slice(0, 12);
}
